Update boyah_builder.yml

diff --git a/.github/workflows/boyah_builder.yml b/.github/workflows/boyah_builder.yml
--- a/.github/workflows/boyah_builder.yml
+++ b/.github/workflows/boyah_builder.yml
@@ -157,44 +157,153 @@ jobs:
           ls -la compiled_images/
           echo "status=success" >> "$GITHUB_OUTPUT"
       
-      - name: Upload OpenWrt to Release
-        uses: ncipollo/release-action@main
-        if: ${{ steps.imagebuilder.outputs.status == 'success' && !cancelled() }}
+  download:
+    name: Download Rootfs
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download Rootfs
+        run: |
+          wget "${{ github.event.inputs.rootfs_url }}"
+          ROOTFS_PATH=$(find ./ -name "*rootfs.tar.gz")
+          echo "ROOTFS_PATH=$ROOTFS_PATH" >> $GITHUB_ENV
+          
+      - name: Upload Rootfs
+        uses: actions/upload-artifact@v4
         with:
-          tag: ${{ env.build_tag }}
-          artifacts: output/*
-          allowUpdates: true
-          removeArtifacts: false
-          replacesArtifacts: true
-          makeLatest: true
-          token: ${{ secrets.AKSI_TOKEN }}
+          name: amlogic-rootfs
+          path: |
+            ${{ env.ROOTFS_PATH }}
 
-      - name: Packaging OpenWrt
-        if: ${{ steps.imagebuilder.outputs.status == 'success' && !cancelled() }}
-        uses: ribel13/aml@main
+  build_specific:
+    name: Build ${{ github.event.inputs.board_version }}
+    runs-on: ubuntu-22.04
+    needs: download
+    if: github.event.inputs.board_version != 'all'
+    steps:
+      - name: Clone Amlogic Builder
+        run: |
+          if [ -d "amlogic-s9xxx-openwrt" ]; then
+            rm -rf amlogic-s9xxx-openwrt
+          fi
+          git clone --depth 1 https://github.com/ribel13/aml.git
+          mkdir -p amlogic-s9xxx-openwrt/openwrt-armsr
+    
+      - name: Download Rootfs
+        uses: actions/download-artifact@v4
         with:
-          openwrt_path: output/*rootfs.tar.gz
-          openwrt_ip: ${{ inputs.openwrt_ip }}
-          openwrt_board: ${{ inputs.openwrt_board }}
-          openwrt_kernel: ${{ inputs.openwrt_kernel }}
-          auto_kernel: ${{ inputs.auto_kernel }}
-          kernel_repo: ${{ inputs.kernel_repo }}
-          kernel_usage: ${{ inputs.kernel_usage }}
-          builder_name: ${{ inputs.builder_name }}
+          name: amlogic-rootfs
+          path: ./amlogic-s9xxx-openwrt/openwrt-armsr/
+          # path: ./Action_ImmortalWrt/releases/download/2026.03.06-0017/openwrt-armsr
+          
+      - name: Build Firmware ${{ github.event.inputs.board_version }} with Kernel ${{ github.event.inputs.kernel_version }}
+        run: |
+          cd amlogic-s9xxx-openwrt
+          sudo ./remake -b ${{ github.event.inputs.board_version }} -k ${{ github.event.inputs.kernel_version }} -s ${{ github.event.inputs.rootfs_size }}
+      
+      - name: Find Firmware
+        run: |
+          FILE_PATH=$(find ./amlogic-s9xxx-openwrt/openwrt/out/ -name "*.img.gz")
+          if [[ -z "$FILE_PATH" ]]; then
+            echo "Error: Tidak ada file firmware ditemukan!"
+            exit 1
+          fi
+          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
 
-      - name: Upload the packaged OpenWrt
-        uses: ncipollo/release-action@main
-        if: ${{ env.PACKAGED_STATUS == 'success' && !cancelled() }}
+      - name: Set up date
+        id: set_date
+        run: |
+          export TZ='Asia/Jakarta'
+          echo "date_time=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
+          
+      - name: Create Release
+        uses: softprops/action-gh-release@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.AKSI_GITHUB }}
         with:
-          tag: ${{ env.build_tag }}
-          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
-          allowUpdates: true
-          removeArtifacts: false
-          replacesArtifacts: true
-          makeLatest: true
-          token: ${{ secrets.AKSI_TOKEN }}
+          name: FRDMX-Wrt ${{ github.event.inputs.openwrt_ver }}
+          tag_name: v${{ github.event.inputs.openwrt_ver }}_k${{ github.event.inputs.kernel_version }}
+          draft: false
+          prerelease: false
+          files: |
+                ${{ env.FILE_PATH }}
           body: |
-            ### OpenWrt Image information
-            - Default IP: `192.168.1.1`
-            - Default username: `root`
-            - Default password: `root`
+            ### Information
+            * Default IP: 192.168.1.1
+            * Default username: frdmx
+
+  build_all:
+    name: Build All
+    runs-on: ubuntu-22.04
+    needs: download
+    if: github.event.inputs.board_version == 'all'
+    strategy:
+      matrix:
+        board_version: 
+          - h96-max-m2
+          - nanopi-r5c
+          - nanopi-r5s
+          - orangepi-5-plus
+          - rk3318-box
+          - s905-beelink-mini
+          - s905-mxqpro-plus
+          - s905l-b860av21u
+          - s905w
+          - s905x2
+          - s905x3
+          - s905x3-h96max
+          - s905x3-x96max
+          - s912
+          - s912-nexbox-a1
+          - s912-nexbox-a2
+          - s922x
+          - tanix-tx6
+    steps:
+      - name: Clone Amlogic Builder
+        run: |
+          if [ -d "amlogic-s9xxx-openwrt" ]; then
+            rm -rf amlogic-s9xxx-openwrt
+          fi
+          git clone --depth 1 https://github.com/ribel13/aml.git
+          mkdir -p amlogic-s9xxx-openwrt/openwrt-armsr
+    
+      - name: Download Rootfs
+        uses: actions/download-artifact@v4
+        with:
+          name: amlogic-rootfs
+          path: ./amlogic-s9xxx-openwrt/openwrt-armsr/
+          
+      - name: Build Firmware ${{ matrix.board_version }} with Kernel ${{ github.event.inputs.kernel_version }}
+        run: |
+          cd amlogic-s9xxx-openwrt/
+          sudo ./remake -b ${{ matrix.board_version }} -k ${{ github.event.inputs.kernel_version }} -s ${{ github.event.inputs.rootfs_size }}
+      
+      - name: Find Firmware
+        run: |
+          FILE_PATH=$(find ./amlogic-s9xxx-openwrt/openwrt/out/ -name "*.img.gz")
+          if [[ -z "$FILE_PATH" ]]; then
+            echo "Error: Tidak ada file firmware ditemukan!"
+            exit 1
+          fi
+          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
+
+      - name: Set up date
+        id: set_date
+        run: |
+          export TZ='Asia/Jakarta'
+          echo "date_time=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
+          
+      - name: Create Release
+        uses: softprops/action-gh-release@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.AKSI_GITHUB }}
+        with:
+          name: FRDM-Wrt ${{ github.event.inputs.openwrt_ver }}
+          tag_name: v${{ github.event.inputs.openwrt_ver }}_k${{ github.event.inputs.kernel_version }}
+          draft: false
+          prerelease: false
+          files: |
+                ${{ env.FILE_PATH }}
+          body: |
+            ### FRDMX-Wrt Information
+            * Default IP: 192.168.1.1
+            * Default username: frdmx
